[package]
name = "apex-sim-deck"
version = "1.0.1"
description = "ApexLaunch Sim Deck"
authors = ["vincentdthe"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = [ "api-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
open = "5.1"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
